# Generated by Django 3.2 on 2022-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='tag',
            field=models.CharField(default='tag', max_length=200),
            preserve_default=False,
        ),
    ]
